config/routes.rb
Rails.application.routes.draw do
  get '/gaiagps', to: 'static_pages#gaia'
	
  resources :flights
  # root 'flights'
  resources :bookings do 
  	resources :passengers
  end
end

app/models/airport.rb
class Airport < ApplicationRecord
	# before_save uppercase_code
	has_many :departing_flights, foreign_key: :start_airport_id, class_name: "Flight"
	has_many :arriving_flights, foreign_key: :finish_airport_id, class_name: "Flight"


	def uppercase_code
		self.code.uppercase!
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
	belongs_to :flight
	has_many :passengers
	accepts_nested_attributes_for :passengers


end

app/models/flight.rb
class Flight < ApplicationRecord
	belongs_to :start_airport, class_name: "Airport"
	belongs_to :finish_airport, class_name: "Airport"

	has_many :bookings#, foreign_key: :flight_id
	has_many :passengers, through: :bookings, source: :passenger#, class_name: "Passenger"

	def start_date_formatted
		self.start_time.strftime("%m/%d/%Y")
	end

end

app/models/passenger.rb
class Passenger < ApplicationRecord
	belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

	def new
		if params[:num_tickets]

			@booking = Booking.new
			params[:num_tickets].to_i.times do |passenger|
				@booking.passengers.new
			end
		end
	end

	def create
		@booking = Booking.new(booking_params)
		# @flight = Flight.find(params[:flight_id])
		# @booking.flight_id = @flight.id 
		# @booking.passengers.each {|x| x.booking_id = @booking.id}

		if @booking.save
			@booking.passengers.each do |passenger|
				PassengerMailer.with(passenger: passenger).welcome_email.deliver_now
				
			end
			redirect_to @booking 

		else
			render action: :new
		end
	end

	def show
		@booking = Booking.find(params[:id])
	end




	private
		def booking_params
			params.require(:booking).permit(:flight_id, :passenger_num,
					:passengers_attributes => [:name, :email])
		end



end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

	def index
		@airport_options = Airport.all.map{ |airport| [airport.code, airport.id]}
		@available_dates = uniq_flight_dates
		if params[:start_airport_id]
			flight_airport = Flight.where(start_airport_id: params[:start_airport_id], finish_airport_id: params[:finish_airport_id])
			@flights = flight_airport.select{|x| date_formatted(x.start_time) == params[:start_time]}
		end
	end

	#returns array of all unique flight dates
	def uniq_flight_dates
		flight_dates = Flight.all.map{ |flight| flight.start_time.strftime("%m/%d/%Y") }
		flight_dates.uniq.sort
	end

	def date_formatted(event_date)
		event_date.strftime("%m/%d/%Y")
	end

	private

		def search_params
			params.require(:flights).permit(:start_airport_id, :finish_airport_id, :start_time)
		end
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController

	def create
		@passenger = Passenger.create(passenger_params)

		# redirect_to bookings_new_path
	end


	private
		def passenger_params
			params.require(:passenger).permit(:name, :email)
		end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def gaia
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/bookings/new.html.erb
<h1>Book Your Flight.</h1> 
<%= params[:flight_id] %>
<%= params[:num_tickets] %>


<% if params[:num_tickets] %>
	<%= form_for @booking do |f| %>
		<%= f.hidden_field(:flight_id, value: params[:flight_id].to_i) %>
		<%= f.hidden_field(:passenger_num, value: params[:num_tickets].to_i) %>
		
			<%= f.fields_for(:passengers) do |p| %>
				<div>
					<h3>Passenger:</h3>
					<%= p.label :name %>
					<%= p.text_field :name %>
					<%= p.label :email %>
					<%= p.text_field :email %>
				
				</div>
			
		<% end %>
		<%= submit_tag("Submit") %>
	<% end %>
<% end %>
				

app/views/bookings/show.html.erb
<h2>Booking</h2>

<h3>Flight Number</h3>
<%= @booking.flight_id %>

<h3>Airports</h3>
Departing Airport:<%= @booking.flight.start_airport.code %><br>  Arrival Airport: <%= @booking.flight.finish_airport.code %>

<h3>Departure Time</h3>
Date: <%= @booking.flight.start_date_formatted %>   Time: <%= @booking.flight.start_time.strftime("%H:%M") %>

<h3>Passengers</h3>
<% @booking.passengers.each do |passenger| %>
	<%= passenger.name %> <br>
<% end %>

app/views/flights/index.html.erb
<h1>Flights</h1>

<%= form_tag(flights_path, method: "get") do |f|%>
	<%= label_tag(:start_airport_id, "From:") %>
	<%= select_tag(:start_airport_id, options_for_select(@airport_options)) %>

	<%= label_tag(:finish_airport_id, "To:") %>
	<%= select_tag(:finish_airport_id, options_for_select(@airport_options)) %>

	<%= label_tag(:start_time, "Departure Day") %>
	<%= select_tag(:start_time, options_for_select(@available_dates)) %>

	<%= label_tag(:num_tickets, "Number of Passengers") %>
	<%= select_tag(:num_tickets, options_for_select([["1",1],["2",2],["3",3],["4",4]])) %>





	<%= submit_tag("Search") %>
	
<% end %>

<% if @flights != nil%>
	<h2>Search Results</h2>

	<%= form_tag('/bookings/new', method: "get") do %>
		
		<% @flights.each do |flight| %>

			From: <%= flight.start_airport.code %>, To: <%= flight.finish_airport.code %>, On: <%= flight.start_date_formatted %>, At: <%= flight.start_time.strftime("%H:%M") %> <%= params[:num_tickets] %>
			<%= radio_button_tag(:flight_id, flight.id) %>  
			<br>

				
		<% end %>
		<%= hidden_field_tag(:num_tickets, params[:num_tickets]) %>
		<%= submit_tag("Book Flight") %>
	<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Torrey Hogan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/gaia.html.erb
<!DOCTYPE html>
<html lang="en">
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
html,body,h1,h2,h3,h4,h5,h6 {font-family: "Roboto", sans-serif;}

</style>
<body>

<!-- Navbar -->

<header id="myFooter">
    <div class="w3-container w3-theme-l2 w3-padding-32">
      <h4>Gaia GPS - How To Instructions</h4>
    </div>

    <div class="w3-container w3-theme-l1">
      <p>Torrey Hogan</p>
    </div>
  </header>

<div class="w3-main" style="margin-left:150px">

	<div >
		<div class="w3-row w3-padding-64">
	   
	      <h1 class="w3-text-teal">Ultralight Backpacking - The Big Three</h1>
	      <p>A heavy pack can make backpacking a burden instead of an adventure. Lightening your backpacking kit can have drastic effects on your daily milage and physical exertion. The Big Three are your three main pieces of gear, which include shelter, sleeping system, and backpack. These items make up the majority of pack weight and are usually the most glaring overweight pieces of gear. The following is a guide to lighten your backpacking gear, focusing on The Big Three.</p>
	    
	  </div>
	 </div>

  <div class="w3-row w3-padding-64">
    <div class="w3-twothird w3-container">
      <h1 class="w3-text-teal">Shelter</h1>
      <p>Shelters provide protection from the elements. Shelters usually consist of tents or tarps. A tent is a fully enclosed shelter that protects from weather and bugs. A tarp is an exposed shelter that offers protection from weather but not bugs. <br><br>Tents come in single wall and double wall. Double wall tents have an external rain proof layer and an internal bug proof layer. The separate layers prevent condensation from forming on the inside of the tent. Double walls provide very good rain protection and ventilation.  Single wall tents only have one layer that doubles as bug and weather protection. Single wall tents can be much lighter than a double wall tent, but the weight reduction comes at a a price. Condensation and breathability are significantly worse in a single wall tent. <br><br> Tarps are the lightest option. They can provide excellent weather protection, but require skill to properly pitch. A single tarp can be pitched many different ways depending on the site. Tarps do not offer bug protection and may be impractical in heavy mosquito areas.  </p>
    </div>
    <div class="w3-third w3-container">
    	<img src="https://s3.amazonaws.com/images.gearjunkie.com/uploads/2016/01/cuben-tent.jpg" width="250">
    </div>
  </div>

  <div class="w3-row">
    <div class="w3-twothird w3-container">
      <h1 class="w3-text-teal">Sleeping System</h1>
      <p>A sleeping system usually consist of a sleeping bag/quilt and a sleeping pad (we won't get into hammocks). <br> <br>
      A sleeping quilt is similar to a sleeping bag, but without out a back(the part you lay on). This cuts down on weight and results in sleeping quilts be slightly lighter than sleeping bags. Whether you choose a sleeping quilt or bag, you the bag should be made with a synthetic shell and down insulation. Ultralight sleeping bags/quilts should weigh around two pounds. <br><br> Sleeping pads insulate you from the cold hard ground. There are three types: air pads, self inflating pads, and closed-cell foam pads. Air pads can be inflated using breath and offer the most comfort, but are prone to puncture. Self-inflating pads are made of an inflatable shell with foam inside the shell. These don't require breath to inflate, but come with a weight penalty. Closed-cell foam pads are made of foam filled with tiny closed air cells. They are very durable, but offer less cushon. Ultralight sleeping pads should weigh around one pound.  </p>
    </div>
    <div class="w3-third w3-container">
    	<img src="http://www.zpacks.com/images/quilts/classic/ultralight-backpacking-quilt-l.jpg" width="250" >
   
    </div>
  </div>

  <div class="w3-row w3-padding-64">
    <div class="w3-twothird w3-container">
      <h1 class="w3-text-teal">Backpack</h1>
      <p>A good backpack should distribute weight between your shoulders and hips allowing all day hiking without irritation. There are three types of backpacks: internal frame, frameless, and external frame. <br><br>Internal frame backpacks have frames made from aluminum or carbon fiber inside the backpack. A frame gives the pack structure allowing the pack weight to be distributed to the hips. The adds comfort but comes at a weight penalty. A good internal framed backpack should weigh around 3 pounds. <br><br>Frameless pack have no rigid structural components. The packs structure is formed through proper packing and compression. Frameless packs are by far the lightest pack option, but require a low pack weight and good packing. Frameless packs should not be used if your pack weight ever exceeds 20 pounds. A good frameless backpack should weigh around 1 pound.<br><br>External frames have tubular aluminum frames outside of the pack fabric. They are the heaviest and are generally considered to be outdated. </p>
    </div>
    <div class="w3-third w3-container">
    	<img src="http://1.bp.blogspot.com/-lQ4m35r4kg0/U64JBBk7oiI/AAAAAAABwyQ/Z8sSilTxQ-M/s1600/2010burnnfront.jpg" height="250">

    </div>
  </div>

  



<!-- END MAIN -->
</div>
  <footer id="myFooter">
    <div class="w3-container w3-theme-l2 w3-padding-32">
      <h4>Torrey Hogan</h4>
    </div>

    <div class="w3-container w3-theme-l1">
      <p>hogantorrey@gmail.com </p>
    </div>
  </footer>



</body>
</html>